### PR TITLE
Add aarch64-pc-windows-msvc

### PR DESCRIPTION
**Pull request by AndrewGaspar**

### CODE REVIEW

**Comment by tarcieri** [comment]
The clippy warnings aren't your problem. Will go ahead and merge then address those myself.

**Comment by AndrewGaspar** [comment]
Yeah, I figured. Thanks!

Would you consider cutting a release?

**Comment by tarcieri** [comment]
Sure. I might do an MSRV bump to 1.40 to make the enums `#[non_exhaustive]`. Hope that's okay (otherwise I can cut a point release too).

**Comment by AndrewGaspar** [comment]
That's fine.

**Pull request merged**
